version: '2'
services:
    architecture-app:
        image: architecture
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://architecture-postgresql:5432/architecture
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    architecture-postgresql:
        extends:
            file: postgresql.yml
            service: architecture-postgresql
